### ISSUE TITLE
ValuSet links to wrong valueset in Profile Viewer 

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffo/hit-base-tool#24]
In the profile viewer, when a value set does not exist in the tables, the link in the profile viewer links to another value set.

example: http://hit-dev.nist.gov:8086/loi-r1/#/cf 
Here MSH-5 hase HL70361_USL as a value set. 
This value set is not yet defined in the table but the tool links to another table HL70361_USL.2 (it should not open any table)

<img width="970" alt="screen shot 2016-09-08 at 10 33 06 am" src="https://cloud.githubusercontent.com/assets/14352180/18353398/d65f4946-75af-11e6-83da-48dba1a9c303.png">

**Comment by haffo** [comment]
fixed and available in next deployment
