### ISSUE TITLE
Profile viewer puts focus on multiple tabs instead of one

### ISSUE THREAD

**Issue by carolinerosin** [haffo/hit-base-tool#25]
When I choose one particular segment, if there is another segment with the same name, both are "highlighted" (see screenshot).
![multiple tabs focus](https://cloud.githubusercontent.com/assets/13591511/18354202/b836cf18-75b2-11e6-90b9-eed44830d3eb.JPG)

**Comment by haffo** [comment]
fixed and available on next deployment
