### ISSUE TITLE
Datatype list in Profile Viewer

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffo/hit-base-tool#27]
There seems to be missing datatypes (at least in the R,RE,C mode) in the datatype list in the profile viewer. 
Bug viewed on http://hit-dev.nist.gov:8086/loi-r1/#/cf . 
For example the ST datatype is missing and is present and required in the profile.

**Comment by haffo** [comment]
I haven't applied the fixes to the datatypes. Will apply
