### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffo/hit-base-tool#29]
In Firefox v48.02 I can not load test step in context base tab.
I also get an empty red notification box  when validating a cf test step.

**Comment by haffonist** [comment]
This might not have anything to do with the browser. Check that your db is not corrupted. Works fine for me on another firefox.

**Comment by ncrouzier-nist** [comment]
I doubt it's the database since the same tool works fine on Chrome.
Will give it a try nonetheless.

**Comment by haffo** [comment]
Is it specific to this version of Firefox ?

Harold

"If I have seen farther than others, it is because I was standing on the shoulders of giants." -- Isaac Newton

**Comment by ncrouzier-nist** [comment]
I'm using v48.0.2 atm.
There seems to be a json/js error when a teststep in the cb tab. Happens on all my tools.
http://hit-dev.nist.gov:8083/ss%2Dr2/#/cb
http://hit-dev.nist.gov:8087/edos%2Dr2/#/cb
http://hit-dev.nist.gov:8086/loi%2Dr1/#/cb
http://hit-dev.nist.gov:8081/lri%2Dr2/#/cb
