### ISSUE TITLE
Validation report bug

### ISSUE THREAD

**Issue by carolinerosin** [haffo/hit-base-tool#31]
The report panel tells me 5 errors, but I can only see one.
![loi validation report bug](https://cloud.githubusercontent.com/assets/13591511/18928297/6cfd42a8-858d-11e6-91df-77b4f244f122.JPG)

**Comment by maxence-lefort** [comment]
Already fixed by Harold (commit 1dd61ee6cc5ba5f16370e2887ee90550a6c886b4)

**Comment by haffo** [comment]
This is already fixed. Please have Nico redeploy.


Harold

"If I have seen farther than others, it is because I was standing on the shoulders of giants." -- Isaac Newton
