### ISSUE TITLE
Suggestion for "Make Public" confirmation  wording

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-base-tool#54]
![image](https://user-images.githubusercontent.com/14842422/41743652-6fa332f0-756f-11e8-96b6-b0b8fdcdbe7c.png)

**Comment by smartinez290** [comment]
![image](https://user-images.githubusercontent.com/14842422/41743880-18f761be-7570-11e8-8c2b-d16fc9f4c06f.png)

**Comment by haffo** [comment]
Done.
