### ISSUE TITLE
Confusing behavior with "start" button and "Test Execution" tab

### ISSUE THREAD

**Issue by ncrouzier-nist** [haffo/hit-base-tool#8]
Some users are confused on how test steps are loaded in the "test execution".
We have a few suggestions to make things clearer.
 * Change "Start" button to "Load test step". Have a tool tip text saying "Load the selected test step" 
 * Add to the tab label the name of the current loaded test step so users know what is loaded even when they  are in the "Test Selection" view. Also had a tool tip saying "View of the "name of test step" environment"
![image](https://cloud.githubusercontent.com/assets/14352180/11277843/4b933614-8eb6-11e5-8e20-e8e33db802e4.png)

Do the same thing for test cases/

**Comment by haffo** [comment]
ok. will do.
